### ISSUE TITLE
Doesn't work for issues from other repositories

### ISSUE THREAD

**Issue by noodny** [nearform/github-action-check-linked-issues#33]
Gave this action a try in https://github.com/nearform/bench-template-mrm-preset/pull/1, and it doesn't seem like it works when referencing issues from other repositories.

**Comment by sameer-coder** [comment]
@noodny I tried to reproduce this but the action seems to work fine when referencing issues from another repository. Check this PR https://github.com/sameer-coder/mrm-preset-nearform/pull/1

**Comment by noodny** [comment]
Maybe it was the specific flow of my actions there:
1. I've first drafted a PR with content `Reference #EXTERNAL_ISSUE_LINK`
2. Transformed that into an actual PR
3. Changed the content to `Resolves #EXTERNAL_ISSUE_LINK`, then tried with `Closes #EXTERNAL_ISSUE_LINK`
4. Eventually @simoneb transferred the referred issue into the same repository, which made it work

**Comment by simoneb** [comment]
Does that apply always or only when the repo containing that issue is private?

**Comment by sameer-coder** [comment]
It applies always. Doesn't matter if a repo is public or private. GitHub tokens created for actions are scoped to the repository they are created for.

**Comment by simoneb** [comment]
Are you sure? Accessing issues in public repos shouldn't require any token whatsoever

**Comment by sameer-coder** [comment]
> Are you sure? Accessing issues in public repos shouldn't require any token whatsoever

yes, you are right. I tested it with a public forked repository and it works fine.
