### ISSUE TITLE
Make action behaviour to fail configurable

### ISSUE THREAD

**Issue by salmanm** [nearform/github-action-check-linked-issues#7]
By default this action sets a failed state when it does not find any linked issues, however we may have a use-case where we only need to be notified via a comment on the PR and not fail the workflow.

- We post a comment on the target PR suggesting to link issues (and perhaps include the suggestion to link it via PR desc just to reiterate the limitation that linking via UI doesn't trigger our workflow)
- We add an input say `mode` which can accept `notify` or `enforce` as values that'd indicate whether the workflow will set failed status or not when it finds no linked issues
- We may want to consider implementing this behavior via check runs (I don't know if it really makes sense but just to research it really) From https://github.com/nearform/github-action-check-linked-issues/pull/1#discussion_r779421452

**Comment by nuragic** [comment]
> we may have a use-case where we only need to be notified via a comment on the PR and not fail the workflow.

I can't see this being useful in a real world scenario. The purpose of this action is "to enforce traceability" so you can only do that by set the step to fail. Regarding a configuration to add a comment, yeah I agree! I think it could be useful.

**Comment by ramonmulia** [comment]
@nuragic @salmanm  In regard to add comment on the target PR, should we always add a comment right after the workflow starts or it would be better just when it fails?

**Comment by nuragic** [comment]
I think that only when it fails. We should also edit (or remove) that comment once the PR is updated and an issue has been linked.

**Comment by ramonmulia** [comment]
I agree, if it passes theres no need to suggest to link the issue.
