### ISSUE TITLE
Release fails after update to release.yml

### ISSUE THREAD

**Issue by krisgrint** [nearform/github-action-check-linked-issues#91]
See e.g. https://github.com/nearform/github-action-check-linked-issues/actions/runs/2370769249

"The specified node version file at: /home/runner/work/github-action-check-linked-issues/github-action-check-linked-issues/.nvmrc does not exist"

**Comment by simoneb** [comment]
ahh that's probably because we're not checking out the source code when releasing

**Comment by krisgrint** [comment]
> ahh that's probably because we're not checking out the source code when releasing

ha, just came to the same conclusion 🙃

should we revert here to just passing the version number? Or add the checkout step to the release workflow?

**Comment by simoneb** [comment]
Let's revert, otherwise we'd have to do this change everywhere. Also let's use just v3 instead of a specific version.
